<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/froala_editor.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/froala_style.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/code_view.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/draggable.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/colors.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/emoticons.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/image_manager.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/image.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/line_breaker.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/table.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/char_counter.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/video.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/fullscreen.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/file.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/quick_insert.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/help.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/third_party/spell_checker.css')}}">
  <link rel="stylesheet" href="{{asset('wysiwyg-editor-master/css/plugins/special_characters.css')}}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css">




  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/froala_editor.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/align.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/char_counter.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/code_beautifier.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/code_view.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/colors.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/draggable.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/emoticons.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/entities.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/file.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/font_size.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/font_family.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/fullscreen.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/image.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/image_manager.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/line_breaker.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/inline_style.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/link.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/lists.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/paragraph_format.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/paragraph_style.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/quick_insert.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/quote.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/table.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/save.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/url.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/video.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/help.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/print.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/third_party/spell_checker.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/special_characters.min.js')}}"></script>
  <script type="text/javascript" src="{{asset('wysiwyg-editor-master/js/plugins/word_paste.min.js')}}"></script>